### ISSUE TITLE
The begin() method samplerate param is the wrong size

### ISSUE THREAD

**Issue by shines2k** [adafruit/Adafruit_TMP007_Library#4]
Adafruit_TMP007::begin() takes a uint8_t samplerate parameter (line 55 Adafruit_TMP007.h), and sets it by default to TMP007_CFG_16SAMPLE, which is 0x0800, and can't fit in 8-bits. This value is then OR'ed together with a few other bits to set the config flag. The intention is to set hires sampling by default, but because this value is truncated to 0 by the compiler (silently), it instead appears to put the chip in 1-sample-average mode.

**Comment by imbenjames** [comment]
Related,  but different issue (I can write a separate issue if you'd like): In the example code comments in the setup function, it is stated that the default sampling is 16 samples to be averaged, but this rate isn't used in the following line in the tmp007.begin() function:

> void setup() { 
  Serial.begin(9600);
  Serial.println("Adafruit TMP007 example");
  // you can also use tmp007.begin(TMP007_CFG_1SAMPLE) or 2SAMPLE/4SAMPLE/8SAMPLE to have
  // lower precision, higher rate sampling. default is TMP007_CFG_16SAMPLE which takes
  // 4 seconds per reading (16 samples)
  if (! tmp007.begin()) {
    Serial.println("No sensor found");
    while (1);
  }
}

**To fix, please insert the TMP007_CFG_16SAMPLE command into the tmp007.begin() function.**
I have verified by looking at the commands written over I2C and looking at the TMP007 datasheet that this code is actually setting up for the 1 sample setting, which only takes .25s instead of 4s to convert. I changed the delay to ensure that new readings were coming up and, indeed, they were.
In other news, y'alls tutorials and code examples have made me a big fan of Adafruit. Thank you!

**Comment by ladyada** [comment]
w00ps, sry for the delay, this is now fixed :)
